name: Bug report
description: Create a new bug report
title: '[Bug]: '
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproduction (if possible, example repository)
      description: Please provide a step by step guide to reproduce the issue
    validations:
      required: true
  - type: textarea
    attributes:
      label: Exception or Error
      description: Please provide error logs if possible.
  - type: input
    attributes:
      label: Version
      description: Coolify's version (see top of your screen).
    validations:
      required: true
