blank_issues_enabled: false
contact_links:
  - name: 🤔 Community Support (Chat)
    url: https://coollabs.io/discord
    about: Reach out to us on Discord.
  - name: 🙋‍♂️ Feature Requests
    url: https://github.com/coollabsio/coolify/discussions/categories/feature-requests-ideas
    about: All feature requests will be discussed here.
